version: '2'
services:

  mongo1:
    image: mongodb
    restart: always
    build: .
    command: mongod --replSet mongodb-raidSet
    ports:
      - 3001:27017
    volumes:
      - /mnt/volume/mongo1/:/data/db/
    links:
      - mongo2
      - mongo3
  mongo2:
    image: mongodb
    restart: always
    command: mongod --replSet mongodb-raidSet
    ports:
      - 3002:27017
    volumes:
      - /mnt/volume/mongo2/:/data/db/

  mongo3:
    image: mongodb
    restart: always
    command: mongod --replSet mongodb-raidSet
    ports:
      - 3003:27017
    volumes:
      - /mnt/volume/mongo3/:/data/db/
